import { Users, Calendar } from "lucide-react";

import type { ArtifactResponse } from "@docu-store/types";
import { Card } from "@/components/ui/Card";
import { EntityTagPanel } from "@/components/EntityTagPanel";
import { HumanCorrectedBadge } from "@/components/documents/HumanCorrectedBadge";
import {
  EditableAuthors,
  EditableDate,
  EditableTags,
} from "@/components/documents/EditableMetadata";

interface OverviewTabProps {
  artifact: ArtifactResponse;
  workspace: string;
  artifactId: string;
  canEdit?: boolean;
}

export function OverviewTab({
  artifact,
  workspace,
  artifactId,
  canEdit = false,
}: OverviewTabProps) {
  return (
    <div className="space-y-6 pt-4">
      {/* Summary */}
      {artifact.summary_candidate?.summary && (
        <Card>
          <h3 className="mb-3 text-sm font-medium text-text-secondary">
            Summary
          </h3>
          <p className="text-sm leading-relaxed text-text-primary">
            {artifact.summary_candidate.summary}
          </p>
          {artifact.summary_candidate.model_name && (
            <p className="mt-3 border-t border-border-subtle pt-2 text-xs text-text-muted">
              Generated by {artifact.summary_candidate.model_name}
            </p>
          )}
        </Card>
      )}

      {/* Authors & Date — shown when present, human-corrected (incl. cleared), or editable */}
      {(canEdit ||
        artifact.author_mentions?.length > 0 ||
        artifact.presentation_date ||
        artifact.human_corrections?.author_mentions ||
        artifact.human_corrections?.presentation_date) && (
        <Card>
          <div className="space-y-3">
            <div className="flex items-start gap-3">
              <Users className="mt-0.5 h-4 w-4 shrink-0 text-text-muted" />
              <div>
                <span className="inline-flex items-center gap-1.5 text-xs font-medium text-text-muted">
                  Authors
                  {artifact.human_corrections?.author_mentions && (
                    <HumanCorrectedBadge info={artifact.human_corrections.author_mentions} />
                  )}
                </span>
                <EditableAuthors artifact={artifact} canEdit={canEdit} />
              </div>
            </div>
            <div className="flex items-center gap-3">
              <Calendar className="h-4 w-4 shrink-0 text-text-muted" />
              <div>
                <span className="text-xs font-medium text-text-muted">
                  Date
                </span>
                <p className="mt-1 inline-flex items-center gap-1.5 text-sm font-medium text-text-primary">
                  <EditableDate artifact={artifact} canEdit={canEdit} />
                  {artifact.human_corrections?.presentation_date && (
                    <HumanCorrectedBadge info={artifact.human_corrections.presentation_date} />
                  )}
                </p>
              </div>
            </div>
          </div>
        </Card>
      )}

      {(canEdit ||
        artifact.tag_mentions?.length > 0 ||
        artifact.human_corrections?.tag_mentions) && (
        <EntityTagPanel
          badge={
            artifact.human_corrections?.tag_mentions && (
              <HumanCorrectedBadge info={artifact.human_corrections.tag_mentions} />
            )
          }
          editor={canEdit ? <EditableTags artifact={artifact} /> : undefined}
          tagMentions={artifact.tag_mentions ?? []}
          workspace={workspace}
          artifactId={artifactId}
        />
      )}

      {/* Metadata */}
      <Card>
        <div className="grid grid-cols-2 gap-4 text-sm md:grid-cols-4">
          <div>
            <span className="text-text-muted">Type</span>
            <p className="mt-1 font-medium text-text-primary">
              {artifact.artifact_type.replace(/_/g, " ")}
            </p>
          </div>
          <div>
            <span className="text-text-muted">MIME Type</span>
            <p className="mt-1 font-mono text-text-primary">
              {artifact.mime_type}
            </p>
          </div>
          <div>
            <span className="text-text-muted">Pages</span>
            <p className="mt-1 font-medium text-text-primary">
              {artifact.pages?.length ?? 0}
            </p>
          </div>
          <div>
            <span className="text-text-muted">Source</span>
            <p className="mt-1 truncate text-text-primary">
              {artifact.source_uri || "—"}
            </p>
          </div>
          <div>
            <span className="text-text-muted">File Name</span>
            <p className="mt-1 font-medium text-text-primary">
              {artifact.source_filename || "—"}
            </p>
          </div>
        </div>
      </Card>
    </div>
  );
}
