/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Artifacts
         * @description List all artifacts with pagination, filtered by permissions.
         */
        get: operations["list_artifacts_artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Artifact
         * @description Retrieve an artifact by ID from the read model.
         */
        get: operations["get_artifact_artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Artifact
         * @description Delete an artifact and all its associated pages.
         */
        delete: operations["delete_artifact_artifacts__artifact_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artifacts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Artifact
         * @description Create a new artifact.
         *
         *     Returns:
         *         201 Created: Artifact successfully created
         *         400 Bad Request: Validation error
         *         500 Internal Server Error: Infrastructure failure (DB unavailable, etc.)
         */
        post: operations["create_artifact_artifacts__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artifacts/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Blob
         * @description Upload a blob to the blob store and create an artifact.
         */
        post: operations["upload_blob_artifacts_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artifacts/{artifact_id}/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Pages
         * @description Add pages to an artifact.
         */
        post: operations["add_pages_artifacts__artifact_id__pages_post"];
        /**
         * Remove Pages
         * @description Remove pages from an artifact.
         */
        delete: operations["remove_pages_artifacts__artifact_id__pages_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artifacts/{artifact_id}/title_mention": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Title Mention
         * @description Update title mention for an artifact.
         */
        patch: operations["update_title_mention_artifacts__artifact_id__title_mention_patch"];
        trace?: never;
    };
    "/artifacts/{artifact_id}/summary_candidate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Summary Candidate
         * @description Update summary candidate for an artifact.
         */
        patch: operations["update_summary_candidate_artifacts__artifact_id__summary_candidate_patch"];
        trace?: never;
    };
    "/artifacts/{artifact_id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Tags
         * @description Update tags for an artifact.
         */
        patch: operations["update_tags_artifacts__artifact_id__tags_patch"];
        trace?: never;
    };
    "/artifacts/{artifact_id}/summarize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Artifact Summarization
         * @description Trigger LLM summarization for an artifact (non-blocking).
         *
         *     Starts the sliding-window artifact summarization Temporal workflow and returns
         *     immediately. The summary is built from all available page-level summaries.
         *
         *     Unlike the automated pipeline trigger this endpoint skips the "all pages done"
         *     precondition — useful for re-running after manual corrections or partial ingestion.
         *     Locked summaries (human corrections) are preserved by the use case.
         */
        post: operations["trigger_artifact_summarization_artifacts__artifact_id__summarize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artifacts/{artifact_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Artifact Summary
         * @description Get the current summary for an artifact from the read model.
         *
         *     Returns the summary_candidate field. Returns 404 if the artifact has no
         *     summary yet.
         */
        get: operations["get_artifact_summary_artifacts__artifact_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artifacts/{artifact_id}/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Artifact Workflows
         * @description Get Temporal workflow statuses for an artifact.
         *
         *     Proxies to Temporal to return the current status of all workflows
         *     associated with the given artifact.
         */
        get: operations["get_artifact_workflows_artifacts__artifact_id__workflows_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artifacts/{artifact_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Artifact Pdf
         * @description Stream the source PDF for an artifact.
         *
         *     Returns the raw PDF binary from blob storage. The artifact must exist
         *     and have a valid storage_location.
         */
        get: operations["stream_artifact_pdf_artifacts__artifact_id__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artifacts/{artifact_id}/pages/{page_index}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Page Image
         * @description Stream the rendered PNG image for a specific page of an artifact.
         *
         *     Returns the pre-rendered page image from blob storage. Page images
         *     are generated during PDF ingestion.
         */
        get: operations["stream_page_image_artifacts__artifact_id__pages__page_index__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artifacts/{artifact_id}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Artifact Permissions
         * @description Get the permission ACL for an artifact with user profiles resolved.
         */
        get: operations["get_artifact_permissions_artifacts__artifact_id__permissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artifacts/{artifact_id}/shares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Share Artifact
         * @description Share an artifact with a user or group.
         *
         *     Only the artifact owner or workspace admin can share.
         *     Sentinel enforces this server-side; the route also fast-fails.
         */
        post: operations["share_artifact_artifacts__artifact_id__shares_post"];
        /**
         * Revoke Artifact Share
         * @description Revoke a share on an artifact.
         */
        delete: operations["revoke_artifact_share_artifacts__artifact_id__shares_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artifacts/{artifact_id}/visibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Artifact Visibility
         * @description Toggle artifact visibility between private and workspace.
         */
        patch: operations["update_artifact_visibility_artifacts__artifact_id__visibility_patch"];
        trace?: never;
    };
    "/pages/{page_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Page
         * @description Retrieve a page by ID from the read model.
         */
        get: operations["get_page_pages__page_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Page
         * @description Delete a page.
         */
        delete: operations["delete_page_pages__page_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Page
         * @description Create a new page.
         *
         *     Returns:
         *         201 Created: Page successfully created
         *         400 Bad Request: Validation error
         *         500 Internal Server Error: Infrastructure failure (DB unavailable, etc.)
         */
        post: operations["create_page_pages__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/{page_id}/tag_mentions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Tag Mentions
         * @description Update tag mentions for a page.
         */
        patch: operations["update_tag_mentions_pages__page_id__tag_mentions_patch"];
        trace?: never;
    };
    "/pages/{page_id}/text_mention": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Text Mention
         * @description Update text mention for a page.
         */
        patch: operations["update_text_mention_pages__page_id__text_mention_patch"];
        trace?: never;
    };
    "/pages/{page_id}/summary_candidate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Summary Candidate
         * @description Update summary candidate for a page.
         */
        patch: operations["update_summary_candidate_pages__page_id__summary_candidate_patch"];
        trace?: never;
    };
    "/pages/{page_id}/compound_mentions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update Compound Mentions
         * @description Add compound_mentions to an existing page.
         */
        post: operations["update_compound_mentions_pages__page_id__compound_mentions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/{page_id}/embeddings/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Embedding Generation
         * @description Trigger embedding generation for a page (non-blocking).
         *
         *     Starts the embedding Temporal workflow and returns immediately with the
         *     initial workflow status. Requires the page to have text content.
         */
        post: operations["trigger_embedding_generation_pages__page_id__embeddings_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/{page_id}/compounds/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Compound Extraction
         * @description Trigger compound extraction for a page (non-blocking).
         *
         *     Starts the CSER ML pipeline as a Temporal workflow and returns immediately
         *     with the initial workflow status. The compounds will be available on the
         *     page once the workflow completes.
         */
        post: operations["trigger_compound_extraction_pages__page_id__compounds_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/{page_id}/compounds/embed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Smiles Embedding
         * @description Trigger SMILES embedding for a page's compounds (non-blocking).
         *
         *     Starts the ChemBERTa embedding Temporal workflow and returns immediately
         *     with the initial workflow status. Requires the page to have extracted
         *     compounds with valid canonical SMILES.
         */
        post: operations["trigger_smiles_embedding_pages__page_id__compounds_embed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/{page_id}/summarize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Page Summarization
         * @description Trigger LLM summarization for a page (non-blocking).
         *
         *     Starts the page summarization Temporal workflow and returns immediately
         *     with the initial workflow status. The summary will be available on the
         *     page once the workflow completes.
         *
         *     Re-triggering is safe — any existing non-locked summary will be replaced.
         *     Locked summaries (human corrections) are preserved by the use case.
         */
        post: operations["trigger_page_summarization_pages__page_id__summarize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/{page_id}/ner/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Ner Extraction
         * @description Trigger NER extraction for a page (non-blocking).
         *
         *     Starts the named-entity recognition Temporal workflow and returns immediately
         *     with the initial workflow status. Extracts compound names, targets, diseases,
         *     and other entities from the page text.
         *
         *     Re-triggering is safe — uses ALLOW_DUPLICATE reuse policy.
         */
        post: operations["trigger_ner_extraction_pages__page_id__ner_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/{page_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Page Summary
         * @description Get the current summary for a page from the read model.
         *
         *     Returns the summary_candidate field from the page read model.
         *     Returns 404 if the page doesn't exist or has no summary yet.
         */
        get: operations["get_page_summary_pages__page_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/{page_id}/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Page Workflows
         * @description Get Temporal workflow statuses for a page.
         *
         *     Proxies to Temporal to return the current status of all workflows
         *     associated with the given page (embedding, compound extraction,
         *     SMILES embedding, summarization).
         */
        get: operations["get_page_workflows_pages__page_id__workflows_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Pages
         * @description Search for similar pages using vector similarity.
         *
         *     Args:
         *         request: Search request with query text and optional filters
         *         container: DI container
         *         auth: Request authentication context
         *
         *     Returns:
         *         Search results with similarity scores
         *
         *     Example:
         *         ```
         *         POST /search/pages
         *         {
         *             "query_text": "machine learning algorithms",
         *             "limit": 10,
         *             "artifact_id": "optional-artifact-uuid",
         *             "score_threshold": 0.7
         *         }
         *         ```
         */
        post: operations["search_pages_search_pages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/pages/{page_id}/generate-embedding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Embedding For Page
         * @description Manually trigger embedding generation for a specific page.
         *
         *     Args:
         *         page_id: UUID of the page to generate embeddings for
         *         container: DI container
         *         auth: Request authentication context
         *         force_regenerate: Whether to overwrite existing embeddings
         *
         *     Useful for:
         *     - Testing the embedding pipeline
         *     - Regenerating embeddings after model changes
         *     - Recovering from failed embedding generation
         *
         *     Args:
         *         page_id: UUID of the page to generate embeddings for
         *         container: DI container
         *         force_regenerate: If True, regenerate even if embedding exists
         *
         *     Returns:
         *         202 Accepted: Embedding generation workflow started
         */
        post: operations["generate_embedding_for_page_search_pages__page_id__generate_embedding_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/compounds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Compounds
         * @description Search for structurally similar compounds using SMILES vector similarity.
         *
         *     The query SMILES is validated, canonicalized, and embedded with ChemBERTa.
         *     Returns compounds from all ingested documents ranked by structural similarity.
         *
         *     Example:
         *         ```
         *         POST /search/compounds
         *         {
         *             "query_smiles": "CC(=O)Oc1ccccc1C(=O)O",
         *             "limit": 10,
         *             "score_threshold": 0.8
         *         }
         *         ```
         */
        post: operations["search_compounds_search_compounds_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/summaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Summaries
         * @description Search page and artifact summaries by semantic similarity.
         *
         *     Queries the unified ``summary_embeddings`` Qdrant collection using dense
         *     vector search.  Results are ordered by cosine similarity.
         *
         *     Use ``entity_type`` to restrict to ``"page"`` or ``"artifact"`` summaries.
         *     Use ``artifact_id`` to search within a specific artifact.
         *
         *     Example:
         *         ```
         *         POST /search/summaries
         *         {
         *             "query_text": "NadD enzyme inhibition",
         *             "limit": 10,
         *             "entity_type": "artifact"
         *         }
         *         ```
         */
        post: operations["search_summaries_search_summaries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/hierarchical": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Hierarchical Search
         * @description Hierarchical cross-collection semantic search.
         *
         *     Searches both the raw text chunk collection (``page_embeddings``) and the
         *     summary collection (``summary_embeddings``) with a single query embedding,
         *     then returns grouped results.
         *
         *     This enables use cases like:
         *     - "Find documents mentioning NadD with compound SACC-111 by TAMU" →
         *       matches at summary level (broad context) and chunk level (exact text)
         *
         *     Set ``include_chunks: false`` to skip chunk search (faster, summary-only).
         *
         *     Returns:
         *         ``summary_hits``: Ordered summary results (page or artifact level).
         *         ``chunk_hits``: Ordered raw chunk results (best chunk per page, deduped).
         *
         *     Example:
         *         ```
         *         POST /search/hierarchical
         *         {
         *             "query_text": "NadD with compound SACC-111 by TAMU",
         *             "limit": 10,
         *             "include_chunks": true
         *         }
         *         ```
         */
        post: operations["hierarchical_search_search_hierarchical_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Health
         * @description Check health of search/embedding services (text, compound, and summary).
         */
        get: operations["search_health_search_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspace/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Members
         * @description Search workspace members by name or email.
         *
         *     Proxies to Sentinel's workspace member list endpoint.
         */
        get: operations["search_members_workspace_members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspace/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Groups
         * @description List groups in the current workspace.
         */
        get: operations["list_groups_workspace_groups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddCompoundMentionsRequest */
        AddCompoundMentionsRequest: {
            /**
             * Page Id
             * Format: uuid
             */
            page_id: string;
            /** Compound Mentions */
            compound_mentions: components["schemas"]["CompoundMention"][];
        };
        /**
         * ArtifactDetailsDTO
         * @description Detailed artifact information for search results.
         */
        ArtifactDetailsDTO: {
            /**
             * Artifact Id
             * Format: uuid
             * @description Unique identifier of the artifact
             */
            artifact_id: string;
            /**
             * Source Uri
             * @description URI pointing to the source of the artifact
             */
            source_uri?: string | null;
            /**
             * Source Filename
             * @description Original filename of the artifact
             */
            source_filename?: string | null;
            /**
             * Artifact Type
             * @description Classification type of the artifact
             */
            artifact_type: string;
            /**
             * Mime Type
             * @description MIME type of the artifact
             */
            mime_type: string;
            /**
             * Storage Location
             * @description Location where the artifact is stored
             */
            storage_location: string;
            /**
             * Page Count
             * @description Number of pages in the artifact
             * @default 0
             */
            page_count: number;
            /**
             * Tags
             * @description List of tags associated with the artifact
             */
            tags?: string[];
            /**
             * Summary
             * @description Summary candidate extracted from the artifact
             */
            summary?: string | null;
            /**
             * Title
             * @description Title mention extracted from the artifact
             */
            title?: string | null;
        };
        /**
         * ArtifactResponse
         * @description Response DTO representing an artifact.
         */
        ArtifactResponse: {
            /**
             * Artifact Id
             * Format: uuid
             * @description Unique identifier of the artifact
             */
            artifact_id: string;
            /**
             * Source Uri
             * @description URI pointing to the source of the artifact
             */
            source_uri?: string | null;
            /**
             * Source Filename
             * @description Original filename of the artifact
             */
            source_filename?: string | null;
            /** @description Classification type of the artifact */
            artifact_type: components["schemas"]["ArtifactType"];
            /** @description MIME type of the artifact */
            mime_type: components["schemas"]["MimeType"];
            /**
             * Storage Location
             * @description Location where the artifact is stored
             */
            storage_location: string;
            /**
             * Workspace Id
             * @description Workspace this artifact belongs to
             */
            workspace_id?: string | null;
            /**
             * Owner Id
             * @description User who created this artifact
             */
            owner_id?: string | null;
            /**
             * Pages
             * @description List of page IDs associated with the artifact
             */
            pages?: string[] | components["schemas"]["PageResponse"][] | null;
            /** @description Title mention extracted from the artifact */
            title_mention?: components["schemas"]["TitleMention"] | null;
            /**
             * Tags
             * @description List of tags associated with the artifact
             */
            tags?: string[];
            /** @description Summary candidate extracted from the artifact */
            summary_candidate?: components["schemas"]["SummaryCandidate"] | null;
        };
        /**
         * ArtifactType
         * @enum {string}
         */
        ArtifactType: "GENERIC_PRESENTATION" | "SCIENTIFIC_PRESENTATION" | "RESEARCH_ARTICLE" | "SCIENTIFIC_DOCUMENT" | "DISCLOSURE_DOCUMENT" | "MINUTE_OF_MEETING" | "UNCLASSIFIED";
        /** Body_upload_blob_artifacts_upload_post */
        Body_upload_blob_artifacts_upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            artifact_type: components["schemas"]["ArtifactType"];
            /** Source Uri */
            source_uri?: string | null;
            /**
             * Visibility
             * @default workspace
             */
            visibility: string;
        };
        /**
         * ChunkHit
         * @description A matching raw text chunk from page_embeddings.
         */
        ChunkHit: {
            /**
             * Page Id
             * Format: uuid
             */
            page_id: string;
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /** Page Index */
            page_index: number;
            /** Score */
            score: number;
            /** Text Preview */
            text_preview?: string | null;
            /** Artifact Name */
            artifact_name?: string | null;
            /** Page Name */
            page_name?: string | null;
        };
        /**
         * CompoundMention
         * @description Represents a chemical compound_mention extracted from a document using NLP.
         *
         *     This value object captures the extracted SMILES notation and associated
         *     compound_mention metadata, including validation status and external identifiers.
         *
         *     Raises:
         *         ValueError: If SMILES is blank or empty.
         */
        CompoundMention: {
            /**
             * Confidence
             * @description Confidence score of the extraction (0.0 to 1.0)
             */
            confidence?: number | null;
            /**
             * Date Extracted
             * @description Timestamp when the content was extracted
             */
            date_extracted?: string | null;
            /**
             * Model Name
             * @description Name of the NLP model used for extraction
             */
            model_name?: string | null;
            /**
             * Additional Model Params
             * @description Additional parameters passed to the extraction model
             */
            additional_model_params?: {
                [key: string]: string;
            } | null;
            /**
             * Pipeline Run Id
             * @description Identifier for the workflow run that produced this extraction
             */
            pipeline_run_id?: string | null;
            /**
             * Smiles
             * @description SMILES notation string (required, cannot be blank)
             */
            smiles: string;
            /**
             * Canonical Smiles
             * @description Canonicalized SMILES representation
             */
            canonical_smiles?: string | null;
            /**
             * Is Smiles Valid
             * @description Indicates whether the SMILES notation is valid
             */
            is_smiles_valid?: boolean | null;
            /**
             * Internal Id
             * @description Internal system identifier for the compound_mention
             */
            internal_id?: string | null;
            /**
             * Cdd Id
             * @description Collaborative Drug Discovery (CDD) identifier
             */
            cdd_id?: string | null;
            /**
             * Chembl Id
             * @description ChEMBL database identifier
             */
            chembl_id?: string | null;
            /**
             * Pdb Id
             * @description Protein Data Bank identifier
             */
            pdb_id?: string | null;
            /**
             * Other Ids
             * @description Set of alternative chemical identifiers
             */
            other_ids?: string[] | null;
            /**
             * Extracted Id
             * @description Primary chemical identifier as extracted from the document
             */
            extracted_id?: string | null;
        };
        /**
         * CompoundSearchRequest
         * @description Request to search for structurally similar compounds by SMILES.
         */
        CompoundSearchRequest: {
            /**
             * Query Smiles
             * @description Query SMILES string (will be canonicalized)
             */
            query_smiles: string;
            /**
             * Limit
             * @default 10
             */
            limit: number;
            /**
             * Artifact Id
             * @description Optional filter to search within a specific artifact
             */
            artifact_id?: string | null;
            /**
             * Score Threshold
             * @description Minimum cosine similarity score (0.0 to 1.0)
             */
            score_threshold?: number | null;
        };
        /**
         * CompoundSearchResponse
         * @description Response containing compound similarity search results.
         */
        CompoundSearchResponse: {
            /** Query Smiles */
            query_smiles: string;
            /** Query Canonical Smiles */
            query_canonical_smiles?: string | null;
            /** Results */
            results: components["schemas"]["CompoundSearchResultDTO"][];
            /** Total Results */
            total_results: number;
            /** Model Used */
            model_used: string;
        };
        /**
         * CompoundSearchResultDTO
         * @description A single compound similarity search result.
         */
        CompoundSearchResultDTO: {
            /** Smiles */
            smiles: string;
            /** Canonical Smiles */
            canonical_smiles?: string | null;
            /**
             * Extracted Id
             * @description Label/ID as extracted from the source document
             */
            extracted_id?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Similarity Score */
            similarity_score: number;
            /**
             * Page Id
             * Format: uuid
             */
            page_id: string;
            /** Page Index */
            page_index: number;
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /** Artifact Name */
            artifact_name?: string | null;
        };
        /**
         * CreateArtifactRequest
         * @description Request DTO for creating a new artifact.
         */
        CreateArtifactRequest: {
            /**
             * Artifact Id
             * @description Optional artifact ID to use instead of generating a new one
             */
            artifact_id?: string | null;
            /**
             * Source Uri
             * @description URI pointing to the source of the artifact
             */
            source_uri?: string | null;
            /**
             * Source Filename
             * @description Original filename of the artifact
             */
            source_filename?: string | null;
            /** @description Classification type of the artifact */
            artifact_type: components["schemas"]["ArtifactType"];
            /** @description MIME type of the artifact */
            mime_type: components["schemas"]["MimeType"];
            /**
             * Storage Location
             * @description Location where the artifact is stored
             */
            storage_location: string;
        };
        /** CreatePageRequest */
        CreatePageRequest: {
            /** Name */
            name: string;
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /**
             * Index
             * @default 0
             */
            index: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HierarchicalSearchRequest
         * @description Request for hierarchical cross-collection search.
         *
         *     Searches both raw text chunks (page_embeddings) and summaries
         *     (summary_embeddings), then merges and re-ranks the results.
         */
        HierarchicalSearchRequest: {
            /** Query Text */
            query_text: string;
            /**
             * Limit
             * @default 10
             */
            limit: number;
            /** Score Threshold */
            score_threshold?: number | null;
            /**
             * Include Chunks
             * @description Whether to include raw chunk hits alongside summary hits.
             * @default true
             */
            include_chunks: boolean;
        };
        /**
         * HierarchicalSearchResponse
         * @description Hierarchical search result grouping summaries with supporting chunks.
         */
        HierarchicalSearchResponse: {
            /** Query */
            query: string;
            /** Summary Hits */
            summary_hits: components["schemas"]["SummaryHit"][];
            /** Chunk Hits */
            chunk_hits: components["schemas"]["ChunkHit"][];
            /** Total Summary Hits */
            total_summary_hits: number;
            /** Total Chunk Hits */
            total_chunk_hits: number;
            /** Model Used */
            model_used: string;
        };
        /**
         * MimeType
         * @description Represent supported MIME types for ingested artifacts.
         * @enum {string}
         */
        MimeType: "application/pdf" | "application/vnd.ms-powerpoint" | "application/vnd.openxmlformats-officedocument.presentationml.presentation" | "application/msword" | "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
        /** PageResponse */
        PageResponse: {
            /**
             * Page Id
             * Format: uuid
             */
            page_id: string;
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /** Name */
            name: string;
            /** Index */
            index: number;
            /** Compound Mentions */
            compound_mentions: components["schemas"]["CompoundMention"][];
            /**
             * Tag Mentions
             * @default []
             */
            tag_mentions: components["schemas"]["TagMention"][];
            text_mention?: components["schemas"]["TextMention"] | null;
            summary_candidate?: components["schemas"]["SummaryCandidate"] | null;
            /** Workspace Id */
            workspace_id?: string | null;
            /** Owner Id */
            owner_id?: string | null;
        };
        /**
         * SearchRequest
         * @description Request to search for similar pages.
         */
        SearchRequest: {
            /** Query Text */
            query_text: string;
            /**
             * Limit
             * @default 10
             */
            limit: number;
            /**
             * Artifact Id
             * @description Optional filter to search within specific artifact
             */
            artifact_id?: string | null;
            /**
             * Score Threshold
             * @description Minimum similarity score (0.0 to 1.0)
             */
            score_threshold?: number | null;
        };
        /**
         * SearchResponse
         * @description Response containing search results.
         */
        SearchResponse: {
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["SearchResultDTO"][];
            /** Total Results */
            total_results: number;
            /** Model Used */
            model_used: string;
        };
        /**
         * SearchResultDTO
         * @description Data transfer object for search results.
         */
        SearchResultDTO: {
            /**
             * Page Id
             * Format: uuid
             */
            page_id: string;
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /** Page Index */
            page_index: number;
            /** Similarity Score */
            similarity_score: number;
            /**
             * Text Preview
             * @description Preview of the page text (if available from read model)
             */
            text_preview?: string | null;
            /**
             * Artifact Name
             * @description Name/filename of the artifact (if available from read model)
             */
            artifact_name?: string | null;
            /** @description Full artifact details including metadata, pages, and tags */
            artifact_details?: components["schemas"]["ArtifactDetailsDTO"] | null;
        };
        /** ShareResourceRequest */
        ShareResourceRequest: {
            /** Grantee Type */
            grantee_type: string;
            /**
             * Grantee Id
             * Format: uuid
             */
            grantee_id: string;
            /**
             * Permission
             * @default view
             */
            permission: string;
        };
        /**
         * SummaryCandidate
         * @description Represents a summary candidate extracted from a page using NLP.
         *
         *     This value object captures the summary content and metadata
         *     about the extraction process, including confidence scores and model details.
         */
        SummaryCandidate: {
            /**
             * Confidence
             * @description Confidence score of the extraction (0.0 to 1.0)
             */
            confidence?: number | null;
            /**
             * Date Extracted
             * @description Timestamp when the content was extracted
             */
            date_extracted?: string | null;
            /**
             * Model Name
             * @description Name of the NLP model used for extraction
             */
            model_name?: string | null;
            /**
             * Additional Model Params
             * @description Additional parameters passed to the extraction model
             */
            additional_model_params?: {
                [key: string]: string;
            } | null;
            /**
             * Pipeline Run Id
             * @description Identifier for the workflow run that produced this extraction
             */
            pipeline_run_id?: string | null;
            /**
             * Summary
             * @description Generated summary content of the page.
             */
            summary?: string | null;
            /**
             * Is Locked
             * @description Indicates if the summary candidate is locked from further modifications
             * @default false
             */
            is_locked: boolean;
            /**
             * Hil Correction
             * @description Human-in-the-loop correction to the generated summary, if any.
             */
            hil_correction?: string | null;
        };
        /**
         * SummaryHit
         * @description A matching summary from summary_embeddings.
         */
        SummaryHit: {
            /**
             * Entity Type
             * @enum {string}
             */
            entity_type: "page" | "artifact";
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /** Score */
            score: number;
            /** Summary Text */
            summary_text?: string | null;
            /** Artifact Title */
            artifact_title?: string | null;
            /** Page Index */
            page_index?: number | null;
        };
        /**
         * SummarySearchRequest
         * @description Request to search page/artifact summaries by semantic similarity.
         */
        SummarySearchRequest: {
            /** Query Text */
            query_text: string;
            /**
             * Limit
             * @default 10
             */
            limit: number;
            /**
             * Entity Type
             * @description Restrict to page or artifact summaries. None = both.
             */
            entity_type?: ("page" | "artifact") | null;
            /**
             * Artifact Id
             * @description Restrict search to a specific artifact.
             */
            artifact_id?: string | null;
            /**
             * Score Threshold
             * @description Minimum cosine similarity score.
             */
            score_threshold?: number | null;
        };
        /**
         * SummarySearchResponse
         * @description Response from summary search.
         */
        SummarySearchResponse: {
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["SummarySearchResultDTO"][];
            /** Total Results */
            total_results: number;
            /** Model Used */
            model_used: string;
        };
        /**
         * SummarySearchResultDTO
         * @description A single hit from the summary embedding collection.
         */
        SummarySearchResultDTO: {
            /**
             * Entity Type
             * @enum {string}
             */
            entity_type: "page" | "artifact";
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /** Similarity Score */
            similarity_score: number;
            /** Summary Text */
            summary_text?: string | null;
            /** Artifact Title */
            artifact_title?: string | null;
            /** Page Index */
            page_index?: number | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /**
         * TagMention
         * @description Represents tag extracted from a page using NLP.
         *
         *     This value object captures the extracted tag content and metadata
         *     about the extraction process, including confidence scores and model details.
         */
        TagMention: {
            /**
             * Confidence
             * @description Confidence score of the extraction (0.0 to 1.0)
             */
            confidence?: number | null;
            /**
             * Date Extracted
             * @description Timestamp when the content was extracted
             */
            date_extracted?: string | null;
            /**
             * Model Name
             * @description Name of the NLP model used for extraction
             */
            model_name?: string | null;
            /**
             * Additional Model Params
             * @description Additional parameters passed to the extraction model
             */
            additional_model_params?: {
                [key: string]: string;
            } | null;
            /**
             * Pipeline Run Id
             * @description Identifier for the workflow run that produced this extraction
             */
            pipeline_run_id?: string | null;
            /** Tag */
            tag: string;
            /** Entity Type */
            entity_type?: string | null;
        };
        /**
         * TextMention
         * @description Represents text extracted from a page using NLP.
         *
         *     This value object captures the extracted text content and metadata
         *     about the extraction process, including confidence scores and model details.
         */
        TextMention: {
            /**
             * Confidence
             * @description Confidence score of the extraction (0.0 to 1.0)
             */
            confidence?: number | null;
            /**
             * Date Extracted
             * @description Timestamp when the content was extracted
             */
            date_extracted?: string | null;
            /**
             * Model Name
             * @description Name of the NLP model used for extraction
             */
            model_name?: string | null;
            /**
             * Additional Model Params
             * @description Additional parameters passed to the extraction model
             */
            additional_model_params?: {
                [key: string]: string;
            } | null;
            /**
             * Pipeline Run Id
             * @description Identifier for the workflow run that produced this extraction
             */
            pipeline_run_id?: string | null;
            /** Text */
            text: string;
        };
        /**
         * TitleMention
         * @description Represents title extracted from a page using NLP.
         *
         *     This value object captures the extracted title content and metadata
         *     about the extraction process, including confidence scores and model details.
         */
        TitleMention: {
            /**
             * Confidence
             * @description Confidence score of the extraction (0.0 to 1.0)
             */
            confidence?: number | null;
            /**
             * Date Extracted
             * @description Timestamp when the content was extracted
             */
            date_extracted?: string | null;
            /**
             * Model Name
             * @description Name of the NLP model used for extraction
             */
            model_name?: string | null;
            /**
             * Additional Model Params
             * @description Additional parameters passed to the extraction model
             */
            additional_model_params?: {
                [key: string]: string;
            } | null;
            /**
             * Pipeline Run Id
             * @description Identifier for the workflow run that produced this extraction
             */
            pipeline_run_id?: string | null;
            /** Title */
            title: string;
        };
        /** UpdateVisibilityRequest */
        UpdateVisibilityRequest: {
            /** Visibility */
            visibility: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkflowStartedResponse */
        WorkflowStartedResponse: {
            /** Workflow Id */
            workflow_id: string;
            /**
             * Status
             * @default started
             */
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_artifacts_artifacts_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_artifact_artifacts__artifact_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_artifact_artifacts__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateArtifactRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_blob_artifacts_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_blob_artifacts_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_pages_artifacts__artifact_id__pages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string[];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_pages_artifacts__artifact_id__pages_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string[];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_title_mention_artifacts__artifact_id__title_mention_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TitleMention"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_summary_candidate_artifacts__artifact_id__summary_candidate_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SummaryCandidate"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_tags_artifacts__artifact_id__tags_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string[];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_artifact_summarization_artifacts__artifact_id__summarize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowStartedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_summary_artifacts__artifact_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_workflows_artifacts__artifact_id__workflows_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_artifact_pdf_artifacts__artifact_id__pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_page_image_artifacts__artifact_id__pages__page_index__image_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
                page_index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_permissions_artifacts__artifact_id__permissions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    share_artifact_artifacts__artifact_id__shares_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShareResourceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_artifact_share_artifacts__artifact_id__shares_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShareResourceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_artifact_visibility_artifacts__artifact_id__visibility_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateVisibilityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_page_pages__page_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                page_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_page_pages__page_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                page_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_page_pages__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_tag_mentions_pages__page_id__tag_mentions_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                page_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagMention"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_text_mention_pages__page_id__text_mention_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                page_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TextMention"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_summary_candidate_pages__page_id__summary_candidate_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                page_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SummaryCandidate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_compound_mentions_pages__page_id__compound_mentions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                page_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCompoundMentionsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_embedding_generation_pages__page_id__embeddings_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                page_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowStartedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_compound_extraction_pages__page_id__compounds_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                page_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowStartedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_smiles_embedding_pages__page_id__compounds_embed_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                page_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowStartedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_page_summarization_pages__page_id__summarize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                page_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowStartedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_ner_extraction_pages__page_id__ner_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                page_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowStartedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_page_summary_pages__page_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                page_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_page_workflows_pages__page_id__workflows_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                page_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_pages_search_pages_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_embedding_for_page_search_pages__page_id__generate_embedding_post: {
        parameters: {
            query?: {
                force_regenerate?: boolean;
            };
            header?: never;
            path: {
                page_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_compounds_search_compounds_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompoundSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompoundSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_summaries_search_summaries_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SummarySearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummarySearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hierarchical_search_search_hierarchical_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HierarchicalSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HierarchicalSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_health_search_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string | {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
    };
    search_members_workspace_members_get: {
        parameters: {
            query?: {
                q?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_groups_workspace_groups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
