from enum import StrEnum


class ArtifactType(StrEnum):
    SCIENTIFIC_PRESENTATION = "SCIENTIFIC_PRESENTATION"
    RESEARCH_ARTICLE = "RESEARCH_ARTICLE"
    SCIENTIFIC_DOCUMENT = "SCIENTIFIC_DOCUMENT"
    DISCLOSURE_DOCUMENT = "DISCLOSURE_DOCUMENT"
    MINUTE_OF_MEETING = "MINUTE_OF_MEETING"
    UNCLASSIFIED = "UNCLASSIFIED"
