from typing import Protocol
from uuid import UUID


class AuthContext(Protocol):
    @property
    def user_id(self) -> UUID: ...
    @property
    def workspace_id(self) -> UUID: ...
    @property
    def workspace_role(self) -> str: ...
    @property
    def is_admin(self) -> bool: ...
    @property
    def name(self) -> str: ...
    def has_role(self, minimum_role: str) -> bool: ...
